/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALink: typeof import('@arco-design/web-vue')['Link']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Avatar: typeof import('./../../src/components/base/Avatar.vue')['default']
    Base: typeof import('./../../src/components/Base.vue')['default']
    ChartBase: typeof import('./../../src/components/chart/ChartBase.vue')['default']
    copy: typeof import('./../../src/components/input/FormItem copy.vue')['default']
    CusEditor: typeof import('./../../src/components/input/CusEditor.vue')['default']
    DataCard: typeof import('./../../src/views/camp/dashboard/components/DataCard.vue')['default']
    DoughnutChart: typeof import('./../../src/views/camp/dashboard/components/DoughnutChart.vue')['default']
    FormItem: typeof import('./../../src/components/input/FormItem.vue')['default']
    IconChristmasTreeOne: typeof import('@icon-park/vue-next')['ChristmasTreeOne']
    IconDiamonds: typeof import('@icon-park/vue-next')['Diamonds']
    IconDocDetail: typeof import('@icon-park/vue-next')['DocDetail']
    IconFolderClose: typeof import('@icon-park/vue-next')['FolderClose']
    IconFullScreen: typeof import('@icon-park/vue-next')['FullScreen']
    IconInbox: typeof import('@icon-park/vue-next')['Inbox']
    IconListTwo: typeof import('@icon-park/vue-next')['ListTwo']
    IconListView: typeof import('@icon-park/vue-next')['ListView']
    IconMe: typeof import('@icon-park/vue-next')['Me']
    IconPlayCycle: typeof import('@icon-park/vue-next')['PlayCycle']
    IconTopBar: typeof import('@icon-park/vue-next')['TopBar']
    IconTreeList: typeof import('@icon-park/vue-next')['TreeList']
    InfoBox: typeof import('./../../src/components/main/info/InfoBox.vue')['default']
    InfoProcess: typeof import('./../../src/components/main/info/InfoProcess.vue')['default']
    InputItem: typeof import('./../../src/components/input/InputItem.vue')['default']
    LayoutIndex: typeof import('./../../src/components/layout/LayoutIndex.vue')['default']
    LayoutMenu: typeof import('./../../src/components/layout/LayoutMenu.vue')['default']
    LeftMenu: typeof import('./../../src/components/layout/LeftMenu.vue')['default']
    LineChart: typeof import('./../../src/views/camp/dashboard/components/LineChart.vue')['default']
    PointBox: typeof import('./../../src/components/main/point/PointBox.vue')['default']
    PointProcess: typeof import('./../../src/components/main/point/PointProcess.vue')['default']
    RollBackground: typeof import('./../../src/views/auth/components/RollBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitScreen: typeof import('./../../src/views/camp/workbench/components/splitScreen/SplitScreen.vue')['default']
    SplitScreenButton: typeof import('./../../src/views/camp/workbench/components/splitScreen/SplitScreenButton.vue')['default']
    TodayCard: typeof import('./../../src/views/camp/dashboard/components/TodayCard.vue')['default']
    TodayDataCard: typeof import('./../../src/views/camp/dashboard/components/TodayDataCard.vue')['default']
    TrendArrow: typeof import('./../../src/components/data/TrendArrow.vue')['default']
  }
}
